local db = require 'std.database':new(5)

-- 先append，屬性的優先級越高
-- 欄位: 屬性名 | 屬性文字格式 | 權重 | 精煉時，該屬性會不會提高 | 詞綴
db:append("物理攻擊力", "+N 物理攻擊力", 0.5, true, "戰意")
db:append("法術攻擊力", "+N 法術攻擊力", 0.75, true, "秘奧")
db:append("物理護甲", "+N 物理護甲", 0.5, true, "不動")
db:append("法術護甲", "+N 法術護甲", 0.75, true)
db:append("無元素傷害", "+N 無元素傷害", 1, false)
db:append("地元素傷害", "+N 地元素傷害", 1, false)
db:append("水元素傷害", "+N 水元素傷害", 1, false)
db:append("火元素傷害", "+N 火元素傷害", 1, false)
db:append("風元素傷害", "+N 風元素傷害", 1, false)
db:append("無元素抗性", "+N 無元素抗性", 1, false)
db:append("地元素抗性", "+N 地元素抗性", 1, false)
db:append("水元素抗性", "+N 水元素抗性", 1, false)
db:append("火元素抗性", "+N 火元素抗性", 1, false)
db:append("風元素抗性", "+N 風元素抗性", 1, false)
db:append("命中", "+N 命中", 1, true)
db:append("閃避", "+N 閃避", 1, true)
db:append("知識", "+N 知識", 2, true)
db:append("技巧", "+N 技巧", 1, true)
db:append("感知", "+N 感知", 1, true)
db:append("耐力", "+N 耐力", 1, true)
db:append("精神", "+N 精神", 1, true, "潮汐")
db:append("急速", "+N 急速", 1, true)
db:append("精通", "+N 精通", 1, true, "專精")
db:append("幸運", "+N 幸運", 1, true)
db:append("靈敏", "+N 靈敏", 1, true)
db:append("物理穿透", "+N 物理穿透", 0.5, false)
db:append("法術穿透", "+N 法術穿透", 0.5, false)
db:append("物理韌性", "+N 物理韌性", 0.75, false)
db:append("法術韌性", "+N 法術韌性", 0.75, false)
db:append("物理格擋", "+N 物理格擋", 0.5, false)
db:append("法術格擋", "+N 法術格擋", 0.5, false)
db:append("物理暴擊", "+N 物理暴擊", 0.75, false)
db:append("法術暴擊", "+N 法術暴擊", 0.75, false)
db:append("攻擊速度", "攻擊速度提高 N%", 0.25, false)
db:append("施法速度", "施法速度提高 N%", 0.25, false)
db:append("固定物理傷害", "+N 固定物理傷害", 1, false)
db:append("額外物理傷害", "+N 額外物理傷害", 2, false)
db:append("額外法術傷害", "+N 額外法術傷害", 2, false)
db:append("特殊物理傷害", "+N 特殊物理傷害", 4, false)
db:append("特殊法術傷害", "+N 特殊法術傷害", 4, false)
db:append("固定物理護甲", "+N 固定物理護甲", 1, false)
db:append("額外物理護甲", "+N 額外物理護甲", 2, false)
db:append("額外法術護甲", "+N 額外法術護甲", 2, false)
db:append("特殊物理護甲", "+N 特殊物理護甲", 4, false)
db:append("特殊法術護甲", "+N 特殊法術護甲", 4, false)
db:append("物理護甲%", "物理護甲提高 N%", 2, false)
db:append("法術護甲%", "法術護甲提高 N%", 2, false)
db:append("近戰減傷", "近戰攻擊造成的傷害降低 N%", 5, false)
db:append("遠程減傷", "遠程攻擊造成的傷害降低 N%", 5, false)
db:append("範圍傷害", "對100碼的敵人造成 N% 的額外傷害", 0.5, false)
db:append("減少魔力消耗", "所有技能的魔力消耗降低 N%", 1, false)
db:append("普通增傷", "對一般生物造成的傷害提高 N%", 1, false)
db:append("菁英增傷", "對菁英生物造成的傷害提高 N%", 2, false)
db:append("稀有菁英增傷", "對稀有菁英生物造成的傷害提高 N%", 3, false)

print(db:query("菁英增傷")[3])
db:update("菁英增傷", nil, nil, 5)
print(db:query("菁英增傷")[3])
print(db._row_)
db:delete("菁英增傷")
print(db._row_)
print(db:query("菁英增傷"))


